version: "3.3"

volumes:
  jenkins: {}

services:
  jenkins:
    image: jenkins/jenkins:lts
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8080:8080"
      - "50000:50000"  
